### ISSUE TITLE
server2 SCSI controller in use

### ISSUE THREAD

**Issue by ghoha** [rdbreak/rhcsa8env#13]
VirtualBox version:
VirtualBox-6.1.x86_64

Vagrant Version:
Vagrant 2.2.7

OS:
Linux 5.4.19-200.fc31.x86_64

Error during vagrant up server2
`Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports`

It is the first time that i use vagrant, but I fixed it in modifying Vagrantfile in this way

```
diff Vagrantfile Vagrantfile.ori 
24,27c24,25
<     if not File.exist?(file_to_disk1)
<       server2.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 2]
<       server2.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]
<     end
-----------------------------
>     server2.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 2]
>     server2.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]
```
I hope that this could be helpful.

**Comment by rdbreak** [comment]
I changed some things around. Run `vagrant destroy -f && git pull && vagrant up` to implement them.

**Comment by rdbreak** [comment]
Also the environment uses virtualbox 6.0 and vagrant 2.2.6, not sure if that is what could be causing it

**Comment by ghoha** [comment]
I got the new version but still the same error:
```
==> server2: Running 'pre-boot' VM customizations...
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "da9434a5-af82-427c-9421-e0ffb337bc9c", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1078 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
```
I have tried to update VBoxGuestAddition, but still the same error.
To fix it I have changed the "if" mentioned in the bug request, could be that in the new Virtual Box version something is changed in how to handle the SATA Controller.

So far is not a big deal.

**Comment by rdbreak** [comment]
I only run into this error with I run `vagrant up` multiple times. Are you sure you're only running `vagrant up` once? If so, would you mind creating a PR with you fix so I can test it? Thanks in advanced.

**Comment by ghoha** [comment]
Sorry I didn't get this message.

You are right I get this only after the first up.
I will test even if the suspend and resume procedure I got the same error.
In any case I will open the PR tonight or tomorrow.

Sorry again for the late reply
