### ISSUE TITLE
Add a couple more drives to server2?

### ISSUE THREAD

**Issue by OpenCloudJedi** [rdbreak/rhcsa8env#14]
Hello, 
Is it possible to add 2 more drives to the server2 VM? It would be nice to be able to setup LVM in /dev/sdb and setup VDO and Stratis on /dev/sdc and /dev/sdd respectively. I attempted to alter the vagrant code that builds the VM's and sets up the hard drive on server2, but have not found success. If this is possible, it would make the environment more flexible for practicing partitioning and advanced storage as presented in the class.

Thanks for your consideration,
OpenCloudJedi

**Comment by OpenCloudJedi** [comment]
I believe it should be some variation of the code in the Vagrantfile I found here:
20     unless File.exist?(file_to_disk1)
 21       server2.customize ['createhd', '--filename', file_to_disk1, '--variant', 'Fixed', '--size', 8 * 1024]
 22       server2.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 2]
 23       server2.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0,     '--type', 'hdd', '--medium', file_to_disk1]
 24       end
 25   end

I have tried a few variations but no success. In the vagrant documentation it says you could do something like this:

Optionally, if you need to attach many disks, you can use Ruby to generate multiple disks for Vagrant to create and attach to your guest:

Vagrant.configure("2") do |config|
  config.vm.define "hashicorp" do |h|
    h.vm.box = "hashicorp/bionic64"
    h.vm.provider :virtualbox

    (0..3).each do |i|
      h.vm.disk :disk, size: "5GB", name: "disk-#{i}"
    end
  end
end

I am unsure how to use this with the code you guys already have. Maybe this is helpful?

OpenCloudJedi

**Comment by rdbreak** [comment]
I'll look into this next week. Thanks!

**Comment by rdbreak** [comment]
The newest push adds an additional drive to server 2 (total of 3 drives)
