### ISSUE TITLE
SSH command responded with a non-zero exit status

### ISSUE THREAD

**Issue by ronrajujohn** [rdbreak/rhcsa8env#16]
Running vagrant on Powershell in Windows as admin and I get the following error when installing the repo. It terminates after this. This is when I do 'vagrant up'. 

`==> repo: Running provisioner: shell...
    repo: Running: inline script
    repo: Updating Subscription Management repositories.
    repo: Unable to read consumer identity
    repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Last metadata expiration check: 0:02:02 ago on Thu 20 Aug 2020 07:39:37 AM PDT.
    repo: [MIRROR] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: [FAILED] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: Updating Subscription Management repositories.
    repo: Unable to read consumer identity
    repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Last metadata expiration check: 0:02:04 ago on Thu 20 Aug 2020 07:39:37 AM PDT.
    repo: No match for argument: sshpass
    repo: Package httpd-2.4.37-10.module+el8+2764+7127e69e.x86_64 is already installed.
    repo: No match for argument: sshpass
    repo: Error: Unable to find a match
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by rdbreak** [comment]
This looks like a DNS issue. Are you using a VPN and is your computer able to reach the outside internet?

**Comment by ronrajujohn** [comment]
Yes, I am using a vpn to connect to the internet. I will disconnect vpn and try again. Thanks! Will provide an update within a few mins.

**Comment by ronrajujohn** [comment]
Yes, its working now! Thank you very much!
