### ISSUE TITLE
The Ruby Homebrew installer is now deprecated

### ISSUE THREAD

**Issue by slimxcz** [rdbreak/rhcsa8env#18]
#!/usr/bin/ruby

STDERR.print <<EOS
Warning: The Ruby Homebrew installer is now deprecated and has been rewritten in
Bash. Please migrate to the following command:
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

EOS

Kernel.exec "/bin/bash", "-c", '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"'

**Comment by rdbreak** [comment]
Would you mind create a PR for this change?
