### ISSUE TITLE
Issue with vagrant up after system reboot

### ISSUE THREAD

**Issue by emondroid** [rdbreak/rhcsa8env#22]
After a system reboot when i try vagrant up, it returns the following error. What is the mistake I'm making?

_[emtiazae@foundation0 rhcsa8env]$ vagrant up
Bringing machine 'server2' up with 'virtualbox' provider...
Bringing machine 'repo' up with 'virtualbox' provider...
Bringing machine 'server1' up with 'virtualbox' provider...
==> server2: Clearing any previously set forwarded ports...
==> server2: Clearing any previously set network interfaces...
==> server2: Preparing network interfaces based on configuration...
    server2: Adapter 1: nat
    server2: Adapter 2: hostonly
    server2: Adapter 3: hostonly
    server2: Adapter 4: hostonly
==> server2: Forwarding ports...
    server2: 22 (guest) => 2222 (host) (adapter 1)
==> server2: Running 'pre-boot' VM customizations...
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "42bf69ca-999a-4267-b7a5-64d5aad4130a", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
[emtiazae@foundation0 rhcsa8env]$_

**Comment by emondroid** [comment]
> After a system reboot when i try vagrant up, it returns the following error. What is the mistake I'm making?
> 
> _[emtiazae@foundation0 rhcsa8env]$ vagrant up
> Bringing machine 'server2' up with 'virtualbox' provider...
> Bringing machine 'repo' up with 'virtualbox' provider...
> Bringing machine 'server1' up with 'virtualbox' provider...
> ==> server2: Clearing any previously set forwarded ports...
> ==> server2: Clearing any previously set network interfaces...
> ==> server2: Preparing network interfaces based on configuration...
> server2: Adapter 1: nat
> server2: Adapter 2: hostonly
> server2: Adapter 3: hostonly
> server2: Adapter 4: hostonly
> ==> server2: Forwarding ports...
> server2: 22 (guest) => 2222 (host) (adapter 1)
> ==> server2: Running 'pre-boot' VM customizations...
> A customization command failed:
> 
> ["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]
> 
> The following error was experienced:
> 
> #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["storagectl", "42bf69ca-999a-4267-b7a5-64d5aad4130a", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]
> 
> Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
> VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
> VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
> 
> > 
> 
> Please fix this customization and try again.
> [emtiazae@foundation0 rhcsa8env]$_

**Comment by Germano0** [comment]
I am also experiencing this problem

```
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "fdc5df0f-aa37-4468-8b19-55ca592f1024", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
```

**Comment by rdbreak** [comment]
Hi all, what host OS are you running on?

**Comment by Germano0** [comment]
CentOS 8

**Comment by victorbrca** [comment]
I'm having the same issue with an Arch host, but it looks like it's a bug on VirtualBox. @rdbreak I have submitted a pull request with the fix.

**Comment by matthowell43** [comment]
Same issue with MacOS 11.1 host. Occurred after using 'vagrant halt', though I've used halt before with no issues.

--------
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "623f7aa5-e7e3-473e-962a-d6652e64374e", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.

**Comment by eldho-varghese** [comment]
I'm also experiencing the similar issue when vagrant reload or vagrant up after halting the server1

A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "0616b1c4-2e4d-494d-a4be-823b994e3530", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage: error: Storage controller named 'SATA Controller' already exists
VBoxManage: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.

**Comment by scor-ch** [comment]
I faced the same issue and was able to get around the problem by removing the huge EMPTY file within the repo system:

```
[vagrant@rhel8 ~]$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
devtmpfs                     389M     0  389M   0% /dev
tmpfs                        406M     0  406M   0% /dev/shm
tmpfs                        406M   11M  395M   3% /run
tmpfs                        406M     0  406M   0% /sys/fs/cgroup
/dev/mapper/rhel_rhel8-root   29G   29G   51M 100% /
/dev/sda1                   1014M  282M  733M  28% /boot
tmpfs                         82M     0   82M   0% /run/user/1000

[root@rhel8 /]# [root@rhel8 /]# ll
total 21431316
..
-rw-r--r--.   1 root root 21945647104 Mar 20 15:11 EMPTY

[root@rhel8 /]# rm EMPTY
rm: remove regular file 'EMPTY'? yes
[root@rhel8 /]#
[root@rhel8 /]#
[root@rhel8 /]# df -h
Filesystem                   Size  Used Avail Use% Mounted on
devtmpfs                     389M     0  389M   0% /dev
tmpfs                        406M     0  406M   0% /dev/shm
tmpfs                        406M   11M  395M   3% /run
tmpfs                        406M     0  406M   0% /sys/fs/cgroup
/dev/mapper/rhel_rhel8-root   29G  8.5G   21G  30% /
/dev/sda1                   1014M  282M  733M  28% /boot
tmpfs                         82M     0   82M   0% /run/user/1000

```
I am not saying this is the correct approach, but at least I was able to get the LAB up and running. To reach that point, I've removed the file as described above (access the system with `ssh repo`) and ran `vagrant up` several times until I got the success message.

```
TASK [Welcome to the RHCSA 8 Study/Test Environment!] **************************
ok: [server1.eight.example.com] =>
  msg:
  - ' The repo server, Server 1, and Server 2 have been set up successfully!'
  - '------------------------------------------------------------------------'
  - ' Server 1 is rebooting.  If you are unable to access it right away,'
  - ' wait a couple moments, then try again.'
  - '------------------------------------------------------------------------'
  - ' Accessing The Systems:'
  - '- Server 1 - 192.168.55.150'
  - '- Server 2 - 192.168.55.151'
  - '- Username/Password - vagrant/vagrant or root/password'
  - '- Access example - `ssh root@192.168.55.150` or `vagrant ssh system1`'
  - ' -----------------------------------------------------------------------'
  - '- Two additional interfaces and drives are on Server 2.'
  - '- Happy Studying!'

PLAY RECAP *********************************************************************
repo.eight.example.com     : ok=9    changed=8    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
server1.eight.example.com  : ok=16   changed=14   unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

==> server1: Running provisioner: shell...
    server1: Running: inline script
```
As said, this might not be a real solution but in my case it helped and probably you can use this information as an indicator to the real issue.

**Comment by baasandorj** [comment]
I had same issue and have updated the Vagrant file, see below!
server2.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
...
...
...
  server2.vm.provider "virtualbox" do |server2|

    unless File.exist?(file_to_disk1)
      server2.customize ['createhd', '--filename', file_to_disk1, '--variant', 'Standard', '--size', 40 * 1024]
      server2.customize ['storagectl', :id, '--name', 'SATA Controller', '--add', 'sata', '--portcount', 2]
      server2.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1]
    end

    unless File.exist?(file_to_disk2)
      server2.customize ['createhd', '--filename', file_to_disk2, '--variant', 'Standard', '--size', 40 * 1024]
      server2.customize ['storageattach', :id,  '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk2]
    end

    server2.memory = "2048"
    
  end
...

**Comment by Zcheng1995** [comment]
Same issue for windows 10 when run vagrant up:
Bringing machine 'server2' up with 'virtualbox' provider...
Bringing machine 'repo' up with 'virtualbox' provider...
Bringing machine 'server1' up with 'virtualbox' provider...
==> server2: Clearing any previously set forwarded ports...
==> server2: Clearing any previously set network interfaces...
==> server2: Preparing network interfaces based on configuration...
    server2: Adapter 1: nat
    server2: Adapter 2: hostonly
    server2: Adapter 3: hostonly
    server2: Adapter 4: hostonly
==> server2: Forwarding ports...
    server2: 22 (guest) => 2222 (host) (adapter 1)
==> server2: Running 'pre-boot' VM customizations...
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "e6816532-a62a-47dd-8af5-0bcc5ef6d6e5", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage.exe: error: Storage controller named 'SATA Controller' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.

**Comment by perezs12** [comment]
Experiencing the same error as others above on my Mac. One work around is to open VirtualBox and start each VM. Then I can ssh into each machine through my terminal.
