### ISSUE TITLE
Server 1 not installed

### ISSUE THREAD

**Issue by rklawns** [rdbreak/rhcsa8env#25]
ran variant up and it only installed server 1 and the repo server. Did a variant destroy and tried it again. Still no server 1. 

Getting this error:

    repo: [MIRROR] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: [FAILED] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]

and this one at the end:

  repo: No match for argument: sshpass
    repo: Error: Unable to find a match
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

Help ?

How can I completely clean the env ? I also have some other vm's setup in virtual box. Is there a limit as to how many I can have ? doc on Virtual box says I am only limited by mem and cpu of host system. 

using Win10 env.

**Comment by rdbreak** [comment]
You can remove the repo directory from your computer and redownload it from Github to clean the environment. You want to make sure your CPU has support for nested virtualization and ensure this feature is turned on in your BIOs.

**Comment by rklawns** [comment]
Ok I think that is my issue. I though it was a space issue but I tried it on a system that had a larger HD but still got the same results. Too busy studying for RHCSA to trouble shoot this further. Thanks.
