### ISSUE TITLE
unable to finish vagrant up install

### ISSUE THREAD

**Issue by jules4412** [rdbreak/rhcsa8env#35]
repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Last metadata expiration check: 0:01:42 ago on Mon 18 Jan 2021 10:25:16 PM PST.
    repo: [MIRROR] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: [FAILED] epel-release-latest-7.noarch.rpm: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: Curl error (6): Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
    repo: Updating Subscription Management repositories.
    repo: Unable to read consumer identity
    repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Last metadata expiration check: 0:02:03 ago on Mon 18 Jan 2021 10:25:16 PM PST.
    repo: No match for argument: sshpass
    repo: Package httpd-2.4.37-10.module+el8+2764+7127e69e.x86_64 is already installed.
    repo: No match for argument: sshpass
    repo: Error: Unable to find a match
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
**To Reproduce**
run vagrant up

**Expected behavior**
doesnt complete fails to resolve  Couldn't resolve host name for https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]
**Screenshots**

**Desktop (please complete the following information):**
 -windows 10

**Additional context**
i can get to both  sites in the browser
ttps://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm [Could not resolve host: dl.fedoraproject.org]

**Comment by rdbreak** [comment]
This looks like a DNS issue. Are you able to reach other websites without issue?
