### ISSUE TITLE
VirtualBox Guest Additions version does not match latest VirtualBox version

### ISSUE THREAD

**Issue by dellipse** [rdbreak/rhcsa8env#37]
The VirtualBox Guest Additions version on server2 does not match latest VirtualBox version.

Guest Additions Version: 5.2.30
VirtualBox Version: 6.0

This might cause issues for users in the future.

1. After running 'vagrant up' for the first time, the error occurs while it is checking for the guest additions in the VM.

**Comment by eldho-varghese** [comment]
Same problem here.. Can you update the vagrant box ?

[server1] GuestAdditions versions on your host (6.1.18) and guest (5.2.30) do not match.
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Error: There are no enabled repos.
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted.
==> server1: Checking for guest additions in VM...
    server1: The guest additions on this VM do not match the installed version of
    server1: VirtualBox! In most cases this is fine, but in rare cases it can
    server1: prevent things such as shared folders from working properly. If you see
    server1: shared folder errors, please make sure the guest additions within the
    server1: virtual machine match the version of VirtualBox you have installed on
    server1: your host and reload your VM.
    server1:
    server1: Guest Additions Version: 5.2.30
    server1: VirtualBox Version: 6.1
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

umount /mnt
Stdout from the command:

Stderr from the command:
umount: /mnt: not mounted.
