### ISSUE TITLE
Slack invite link is not working

### ISSUE THREAD

**Issue by ilanfroi** [rdbreak/rhcsa8env#38]
Hello,
Thank you for your contribute. 
It seems that the invite link to Slack is no longer active and working. 
This is the error message I get when following:
https://join.slack.com/t/redhat-certs/shared_invite/zt-7ju3rz7b-_G3Njp3PDwdBG_81SwPeLA

********* SNIP ***********
This link is no longer active

To join this workspace, you’ll need to ask the person who originally invited you for a new link.
********* SNIP ***********
thank you

**Comment by PaulVerhoeven1** [comment]
This is because Slack changed its policy how long a link will be valid (default is now 30 days).
 Here is a new link: https://join.slack.com/t/redhat-certs/shared_invite/zt-k6ew2jxh-fnBYw2Pw4~PQQE~Nse~wCQ
