### ISSUE TITLE
Access repo help

### ISSUE THREAD

**Issue by bartbus7** [rdbreak/rhcsa8env#39]
Exactly what command is needed to access this link? dnf install nor yum install don't work.
"There is a Repo/AppStream available to use from http://repo.eight.example.com/BaseOS and http://repo.eight.example.com/AppStream"

**Comment by rdbreak** [comment]
These links are used to access the repo server once the environment is up and running. Can you provide your repo file(s) content?

**Comment by bartbus7** [comment]
When I look in the repo server under /etc/yum.repos.d/ there is main.repo, epel.repo, and epel-testing.repo. I was finally able to scp copy these repos over to server1 and 2, but it fails yum repolist: failed to sync cache for repo 'AppStream' / 'BaseOS'. I was able to do yum repolist for the epel.repo. I also couldn't access the http links.

**Comment by bartbus7** [comment]
I have removed and rebuilt the 2 servers, 1 and 2, and repo 30 times and still get failed to sync cache for repo 'AppStream' / 'BaseOS'. This has never worked.

**Comment by rdbreak** [comment]
I'm not having trouble on my end but it must be something. Please paste the contents of the main repo file here

**Comment by bartbus7** [comment]
Here's the main repo contents, which is exactly the same on both server 1 and 2.
![image](https://user-images.githubusercontent.com/58150488/110371786-0e71b900-8013-11eb-9f55-897db89c4c81.png)
![mainrepo](https://user-images.githubusercontent.com/58150488/110371911-3c56fd80-8013-11eb-8ea3-871e070f6377.PNG)

**Comment by bartbus7** [comment]
How should main.repo be put on server1 and 2? I've been logging into repo server and scp copying it over to server1 and 2. Maybe I should be doing it some other way.

**Comment by bartbus7** [comment]
Issue resolved. Just used scp from repo server to copy the repos to the 2 vms.
