### ISSUE TITLE
vagrant up fails on rsync out of space

### ISSUE THREAD

**Issue by sparinisi** [rdbreak/rhcsa8env#43]
on my Win-10 system the vagrant up fails with the error below. I also tries increasing disk size to 10G within the vagrant file. Any help would be appreciated. Thanks
--------------------------------------------------------------
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/c/RHEL8Exam/rhcsa8env-master/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/spari/.vagrant.d/boxes/rdbreak-VAGRANTSLASH-rhel8repo/1.1/virtualbox/vagrant_private_key'" "--exclude" ".vagrant/" "--exclude" ".git/" "/cygdrive/c/RHEL8Exam/rhcsa8env-master/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: write failed on "/vagrant/disk-0-1.vdi": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

**Comment by bkarankar** [comment]
edit Vagrantfile file as:

remove line number 17 and paste below code
server2.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
remove line number 66 and paste below code
repo.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
remove line number 77 and paste below code
server1.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
then
4) line number 64 => remove sshpass (it's specified two times so remove one.)
5) if you are on rhel8.x then update line 64 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

You can still found /EMPTY file in Repo VM. it's seems like image issue. you can run "sudo truncate -s0 /EMPTY" to make space.

**Comment by franchyze923** [comment]
@bkarankar Thanks for this. I found the `Vagrantfile-new-by-bkarankar` file in the repo and renamed to `Vagrantfile`. It took me a while to find this, any idea why `Vagrantfile-new-by-bkarankar` isn't the default `Vagrantfile`? This fixed my issues.
