### ISSUE TITLE
error when attempting to rsync a synced folder

### ISSUE THREAD

**Issue by najib277** [rdbreak/rhcsa8env#47]
getting below error while try to set environment
 
==> repo: Installing rsync to the VM...
==> repo: Rsyncing folder: /cygdrive/e/rhcsa8env-master/rhcsa8env-master/ => /vagrant
==> repo:   - Exclude: [".vagrant/", ".git/"]
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/e/rhcsa8env-master/rhcsa8env-master/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/Inaya/.vagrant.d/boxes/rdbreak-VAGRANTSLASH-rhel8repo/1.1/virtualbox/vagrant_private_key'" "--exclude" ".vagrant/" "--exclude" ".git/" "/cygdrive/e/rhcsa8env-master/rhcsa8env-master/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: write failed on "/vagrant/disk-0-1.vdi": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

**Comment by bkarankar** [comment]
edit Vagrantfile file as:

1) remove line number 17 and paste below code
`server2.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
`
2) remove line number 66 and paste below code
`	repo.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
`
3) remove line number 77 and paste below code
`	server1.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "disk-0-1.vdi", "disk-0-2.vdi", ".github"]
`

then 
4) line number 64 => remove sshpass (it's specified two times so remove one.)
5) if you are on rhel8.x then update line 64 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

You can still found /EMPTY file in Repo VM. it's seems like image issue. you can run "sudo truncate -s0 /EMPTY" to make space.

**Comment by Truesh00ter** [comment]
@bkarankar thanks a lot! these things fixed it for me (just starting out on from a W10 machine). For anyone with a fresh install like me. The last command, to truncate the directory that caused this issue, you will need to open VirtualBox and log in with the credentials listed in the README.md (this far in you will see two VMs in VirtualBox like bkarankar says log in to repo VM and run his command).

**Comment by GrigasS** [comment]
thank you @bkarankar . With the edits, everything is deploying as it should!

**Comment by bkarankar** [comment]
Thanks for the confirmation @GrigasS
