### ISSUE TITLE
system bricks upon persistent editing of grub2 boot loader config 

### ISSUE THREAD

**Issue by Reiahx** [rdbreak/rhcsa8env#5]
**As of this issue submission repo is using image Oracle 8 **

as title says 

![Screen Shot 2019-08-12 at 3 39 35 AM](https://user-images.githubusercontent.com/26658835/62912080-9834a400-bd54-11e9-924a-ca38f7ebbe11.png)

**Comment by rdbreak** [comment]
This appears to be an issue with the GRUB2 boot loader in version 8 since it differs from that of RHEL 7. It should be fixed in subsequent releases.

https://access.redhat.com/solutions/3710121

**Comment by Reiahx** [comment]
i see...can't access the whole article because it is subscriber exclusive content but if that is the gist of it then ok.
