### ISSUE TITLE
rdbreak/rhel8node' could not be found

### ISSUE THREAD

**Issue by dhongadeap** [rdbreak/rhcsa8env#50]
The box 'rdbreak/rhel8node' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/rdbreak/rhel8node"]
Error: schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.

**Comment by taaaamer** [comment]
@dhongadeap 
I'm facing the same issue :(
did you find any solution for that?

Thank you in advance.

**Comment by kompressorie7175** [comment]
Has there been any fix to this issue? I am experiencing exactly same problem.
If any suggestions please...thanks
