### ISSUE TITLE
rhcsa8env on Fedora 34

### ISSUE THREAD

**Issue by firstmattheo** [rdbreak/rhcsa8env#58]
After installing/Download and unzip under /bin/rhcsa8env
I do vagrant up with root I get this:
_"No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider."

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser firefox

**Additional context**

**Comment by rdbreak** [comment]
Hi Mattheo, thank you for you sponsorship! For this, I've put your request at the top of my list. I've been working on a big update to the environment that should address your concerns.

Thanks again for you sponsorship! Let me know if you have any other concerns

**Comment by CallMeMiyosh** [comment]
I've got the same problem on Fedora 35,
System Fedora 35
Browser firefox
Installed Version: 2.2.16
Vbox version
Packages providing this file are:

'VirtualBox-6.1'

'VirtualBox-7.0'



[root@exam01 rhcsa8env-master]# vagrant up

No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as

"providers", to provide Vagrant with resources to run development

environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which

is available for free on all major platforms.

If you believe you already have a provider available, make sure it

is properly installed and configured. You can see more details about

why a particular provider isn't working by forcing usage with

`vagrant up --provider=PROVIDER`, which should give you a more specific

error message for that particular provider.
