### ISSUE TITLE
Link expired

### ISSUE THREAD

**Issue by gylli251** [rdbreak/rhcsa8env#59]
Hey is it possible to get a link for the slack group again?

Got my test on friday! :)

Thanks in advance

**Comment by rdbreak** [comment]
This is one irritating feature of Slack invite links: Their never expiring links seem to expire  ¯\_(ツ)_/¯ 

[Here](https://join.slack.com/t/redhat-certs/shared_invite/zt-qgnlqcck-_0Od17IO5xlkV5BXWaEEEg) is another one
