### ISSUE TITLE
New Mac User

### ISSUE THREAD

**Issue by Allen0721** [rdbreak/rhcsa8env#7]
I am new to Mac and am trying to install this on Mac. It all goes well but when I run it I have to run it with sudo from the command line. I already had virtual box installed but it does not see the VM's unless i run as sudo, and when I do then my other VM's don't appear.

What did I do wrong?

**Comment by rdbreak** [comment]
When running `vagrant up`, are you seeing any errors? If so, can you post the output here.

**Comment by rdbreak** [comment]
Closing for lack of response
