### ISSUE TITLE
Storage error after trying to run vagrant up from vagrant halt state.

### ISSUE THREAD

**Issue by MrFraser95** [rdbreak/rhcsa8env#72]
Hi,
I'm getting this error when i try to run vagrant up from vagrant halt state.

PS C:\Users\Administrator\bin\rhcsa8env-master> vagrant up
Bringing machine 'server2' up with 'virtualbox' provider...
Bringing machine 'repo' up with 'virtualbox' provider...
Bringing machine 'server1' up with 'virtualbox' provider...
==> server2: Clearing any previously set forwarded ports...
==> server2: Fixed port collision for 22 => 2222. Now on port 2201.
==> server2: Clearing any previously set network interfaces...
==> server2: Preparing network interfaces based on configuration...
    server2: Adapter 1: nat
    server2: Adapter 2: hostonly
    server2: Adapter 3: hostonly
    server2: Adapter 4: hostonly
==> server2: Forwarding ports...
    server2: 22 (guest) => 2201 (host) (adapter 1)
==> server2: Running 'pre-boot' VM customizations...
A customization command failed:

["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--portcount", 2]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storagectl", "b04c4829-42e5-4ba9-8049-dfa1b673613a", "--name", "SATA Controller", "--add", "sata", "--portcount", "2"]

Stderr: VBoxManage.exe: error: Storage controller named 'SATA Controller' already exists
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_IN_USE (0x80bb000c), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "AddStorageController(Bstr(pszCtl).raw(), StorageBus_SATA, ctl.asOutParam())" at line 1080 of file VBoxManageStorageController.cpp
>

Please fix this customization and try again.
PS C:\Users\Administrator\bin\rhcsa8env-master>

**Comment by bcl-49** [comment]
There is a resolution to this that worked for me in the issues closed section. Here is a link to the comment that worked:
https://github.com/rdbreak/rhcsa8env/issues/55#issuecomment-1019375717
