### ISSUE TITLE
Unable to run ipa machine

### ISSUE THREAD

**Issue by cybersiddiqui** [rdbreak/rhcsa8env#9]
**repo: Failed to synchronize cache for repo 'epel', ignoring this repo.**
    repo: epel-release-latest-7.noarch.rpm                 11 kB/s |  15 kB     00:01    
    repo: Package epel-release-7-12.noarch is already installed.
    repo: Dependencies resolved.
    repo: Nothing to do.
    repo: Complete!
    repo: Updating Subscription Management repositories.
    repo: Unable to read consumer identity
    repo: This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
    repo: Extra Packages for Enterprise Linux 7 - x86_64  0.0  B/s |   0  B     00:01    
    **repo: Failed to synchronize cache for repo 'epel', ignoring this repo.**
    repo: Last metadata expiration check: 0:00:16 ago on Fri 27 Dec 2019 05:29:00 AM PST.
    **repo: No match for argument: sshpass**
    repo: Package httpd-2.4.37-10.module+el8+2764+7127e69e.x86_64 is already installed.
    repo: No match for argument: sshpass
    repo: Error: Unable to find a match
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
$ vagrant status                       
Current machine states:

system                    running (virtualbox)
repo                      running (virtualbox)
**ipa                       not created (virtualbox)**

**Comment by rdbreak** [comment]
I just tested this environment out and didn't run into this. Can you try `vagrant destroy -f ; git pull ; vagrant up` and see if you run into the same issue?

**Comment by rdbreak** [comment]
Closing for lack of information
